---
# Setup kubernetes cluster. Be sure to run the master play before the
# other cluster nodes.

# XXX: perhaps a refactor to put swap-off as `pre_tasks` and move the
# `import_role` statements to a `roles` key.
- hosts: k8s_nodes
  vars_files:
    - vars/k8s/{{ env }}.yml
    - vars/k8s/geerlingguy.pip.yml
    - vars/k8s/geerlingguy.docker-{{ env }}.yml
    - vars/k8s/geerlingguy.kubernetes.yml
  pre_tasks:
    # See https://serverfault.com/a/931984/426435 and discussion
    # https://github.com/kubernetes/kubernetes/issues/53533
    #
    # If you want to enable swap see geerlingguy.kubernetes
    # (https://github.com/geerlingguy/ansible-role-kubernetes)
    # For the appropriate way to setup the `kubernetes_kubelet_extra_args`
    # variable to prevent errors.
    - name: disable swap
      block:
        - name: Remove swapfile from /etc/fstab
          mount:
            name: "{{ item }}"
            fstype: swap
            state: absent
          with_items:
            - swap
            - none

        - name: Disable swap
          command: swapoff -a
          when: ansible_swaptotal_mb > 0
      tags: swap
    - name: conditionally include variables for master
      include_vars:
        file: vars/k8s/geerlingguy.kubernetes-master.yml
      when: "'k8s_master' in group_names"

    - name: conditionally include variables for nodes other than master
      include_vars:
        file: vars/k8s/geerlingguy.kubernetes-node.yml
      when: "'k8s_master' not in group_names"

  roles:
    - role: geerlingguy.pip
      tags: pip

    - role: geerlingguy.docker
      tags: docker

    - role: geerlingguy.kubernetes
      tags: kubernetes
  tasks:
    - name: Setup kubeconfig for vagrant user
      block:
        - name: create kube config directory for user vagrant
          file:
            path: /home/vagrant/.kube
            state: directory

        # May use the template module if using a custom config.
        - name: copy config kube config for user vagrant
          copy:
            remote_src: yes
            src: /etc/kubernetes/admin.conf
            dest: /home/vagrant/.kube/config
            # Depending on the Vagrant synced folder type this may be
            # unecessary, ineffective or may not work.
            owner: vagrant
            group: vagrant
      when: env == 'dev' and 'k8s_master' in group_names
      tags: vagrant_kubeconfig
