---
- hosts: k8s_nodes
  vars_files:
    - vars/k8s/{{ env }}.yml
    - vars/k8s/geerlingguy.pip.yml
    - vars/k8s/geerlingguy.docker-{{ env }}.yml
    - vars/k8s/geerlingguy.kubernetes.yml
  tasks:
    - name: conditionally include variables for master
      include_vars:
        file: vars/k8s/geerlingguy.kubernetes-master.yml
      when: "'k8s_master' in group_names"

    - name: conditionally include variables for nodes other than master
      include_vars:
        file: vars/k8s/geerlingguy.kubernetes-node.yml
      when: "'k8s_master' not in group_names"

    - name: import common tasks for both master and other nodes
      import_tasks: tasks/k8s.yml

    - name: Setup kubeconfig for vagrant user
      block:
        - name: create kube config directory for user vagrant
          file:
            path: /home/vagrant/.kube
            state: directory

        # May use the template module if using a custom config.
        - name: copy config kube config for user vagrant
          copy:
            remote_src: yes
            src: /etc/kubernetes/admin.conf
            dest: /home/vagrant/.kube/config
            # Depending on the Vagrant synced folder type this may be
            # unecessary, ineffective or may not work.
            owner: vagrant
            group: vagrant
      when: env == 'dev' and 'k8s_master' in group_names
      tags: vagrant_kubeconfig

    # FIXME: the apropriate way to do is to verify if the config is applied,
    # then download and apply, perhaps using get_url + kubctl modules.
    # - name: Install calico pod network
    #   become: false
    #   command: kubectl create -f https://docs.projectcalico.org/v3.4/getting-started/kubernetes/installation/hosted/calico.yaml
    #   tags: calico

    # This may not work if join command references 10.0.2.15 (host-only
    # network)
    #
    # Also, perhaps the geerlingguy.kubernetes role already deal with
    # joining.
    # - name: Generate join command
    #   command: kubeadm token create --print-join-command
    #   register: join_command

    # - name: Copy join command to local file
    #   local_action:
    #     module: copy
    #     content: "{{ join_command.stdout_lines[0] }}"
    #     dest: "./join-command"

  handlers:
    - name: import common handlers for k8s
      import_tasks: handlers/k8s.yml
